M48
; DRILL file {KiCad 9.0.2} date 2026-04-02T07:38:21+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-02T07:38:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.250
%
G90
G05
T1
X81.083Y-19.869
X81.083Y-21.901
X86.163Y-20.885
T2
X55.0Y-4.9
M30
